services:
  whisper:
    image: "whisper-api:latest"
    build:
      context: whisper
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # tiny.en, tiny, base.en, base, small.en, small, medium.en, medium,
      # large-v1, large-v2, large-v3, large, distil-large-v2,
      # distil-medium.en, distil-small.en
      WHISPER_MODEL: "base"
      # "auto" or "cuda" or "cpu"
      DEVICE: "auto"
      # See https://opennmt.net/CTranslate2/quantization.html
      COMPUTE_TYPE: "int8"
    volumes:
      - ./models:/app/models
